// Adapter-file builder for the connect flow. detectFramework (from @stigmergy/connect) proposes the
// per-framework wiring snippet, but every snippet assumes an `engine` already exists. The engine is
// the actual missing piece on a fresh integration: without it, a lazily-loaded adapter degrades to a
// no-op and nothing ever reaches the substrate. buildSetupPreamble produces that missing part (install
// the packages, build one engine on the SAME database the Studio reads), so the user or their coding
// agent gets the complete recipe instead of a snippet with an undefined variable. No React or Electron
// import, so the monorepo vitest covers it. Integration-specific hints live in integrations.ts.
import type { FrameworkDetection } from '@stigmergy/connect'

export interface AdapterFile {
  filename: string
  content: string
}

const DEFAULT_SUBSTRATE = '~/.stigmergy/pheromone.db'

/** The part the framework snippets leave out: install the packages and construct one engine on the
 * exact same substrate the Studio watches. Pointing the engine at a different DB is the most common
 * reason a "wired" loop never shows up, so the path is embedded literally. */
export function buildSetupPreamble(substratePath: string): string {
  const dbPath = substratePath.trim() === '' ? DEFAULT_SUBSTRATE : substratePath
  return [
    '// 1. Install the packages in your loop project:',
    '//    npm install @agentic-stigmergy/loop @agentic-stigmergy/core @stigmergy/storage-better-sqlite3 @stigmergy/embedding-transformers',
    '// 2. Build one engine on the SAME database Stigmergy Studio watches (this path matters):',
    "import { createEngine } from '@agentic-stigmergy/core'",
    "import { BetterSqlite3Storage } from '@stigmergy/storage-better-sqlite3'",
    "import { TransformersEmbedding } from '@stigmergy/embedding-transformers'",
    // Default to the REAL model: it produces the same 384-dim space the daemon and Studio use, so
    // ranking is meaningful. FakeEmbedding (64-dim, from @agentic-stigmergy/core) is only a quick offline stub.
    `const engine = await createEngine({ storage: new BetterSqlite3Storage(${JSON.stringify(dbPath)}), embedding: new TransformersEmbedding() })`,
    '// (for a quick offline smoke you can swap TransformersEmbedding for FakeEmbedding from @agentic-stigmergy/core)',
    '// 3. Reuse that one engine in the wiring below:',
  ].join('\n')
}

/** Wrap a framework detection's snippet into a copy-paste adapter file. The Studio shows the content
 * as a diff and writes it only after the user confirms. The preamble makes the engine explicit so the
 * snippet's `engine` is not left undefined. */
export function buildAdapterFile(detection: FrameworkDetection, substratePath = ''): AdapterFile {
  const header = [
    '// Generated by Stigmergy Studio.',
    `// Detected framework: ${detection.framework}.`,
    '// Wire this into your loop; the connection turns green on the first consult plus event.',
    '',
  ].join('\n')
  const content = [header, buildSetupPreamble(substratePath), '', detection.snippet, ''].join('\n')
  return { filename: 'stigmergy.connect.ts', content }
}

/** Build a prompt the user can paste into their coding agent (Claude Code, Cursor, ...) so the agent
 * wires Stigmergy into the loop at the right places, instead of the user editing by hand. Carries the
 * full recipe (install plus engine plus the framework snippet) and is explicit that Stigmergy only
 * observes (it must not change behaviour). */
export function buildAgentPrompt(detection: FrameworkDetection, substratePath = ''): string {
  return [
    'You are working in my agent-loop codebase. Integrate Stigmergy so it observes the loop and learns',
    'which tools to surface. Stigmergy only observes; do not change what the agent does or invent tools.',
    `Detected framework: ${detection.framework}${detection.integration ? ` (install ${detection.integration})` : ''}.`,
    '',
    'First set up the engine (this is the part most integrations miss):',
    '',
    buildSetupPreamble(substratePath),
    '',
    'Then wire these calls in at the idiomatic places: consult before the model / tool-selection step,',
    'wrap the tools, then call end and GRADE the turn (accept on a clean success, iterate on a revision,',
    'abandon on a failed run) after each run resolves. Reuse the one engine above:',
    '',
    detection.snippet,
    '',
    'Keep the existing behaviour. After wiring, the Connect verify in Stigmergy Studio turns green on the',
    'first consult plus event.',
  ].join('\n')
}

// --- Daemon-client recipe (FEAT-04-09 / FEAT-04-10) -------------------------------------------------
// For a host that cannot embed an engine (e.g. the Obsidian sandbox) or simply wants Stigmergy as one
// external service: Stigmergy runs as a separate daemon (real model, real DB, the substrate), the host
// is a thin client over the daemon's Unix socket. The host installs only @agentic-stigmergy/client, holds no
// engine, no model, no storage. This is the host-agnostic onboarding path the Studio offers.

const DEFAULT_SOCKET = '~/.stigmergy/stigmergy.sock'

function resolveSocket(socketPath: string): string {
  return socketPath.trim() === '' ? DEFAULT_SOCKET : socketPath
}

/** The shell command to start the daemon once (a separate process that owns the model and the DB). The
 * Studio shows this so the operator can copy-run it; the same socket path is used in the host recipe. */
export function buildDaemonStartCommand(substratePath = '', socketPath = ''): string {
  const db = substratePath.trim() === '' ? DEFAULT_SUBSTRATE : substratePath
  const sock = resolveSocket(socketPath)
  return `STIGMERGY_DAEMON_SOCKET=${JSON.stringify(sock)} stigmergyd ${JSON.stringify(db)}`
}

/** The host-side wiring for the daemon-client model: install the thin client, connect to the socket,
 * register the host's tools once, then per turn report the task and ask which tools to surface, and
 * report the outcome so the daemon learns. Framework-independent; the host adapts the tool source. */
export function buildDaemonClientRecipe(socketPath = ''): string {
  const sock = resolveSocket(socketPath)
  return [
    '// 1. Install the thin client and the loop facade (no engine, model or DB in your loop):',
    '//    npm install @agentic-stigmergy/client @agentic-stigmergy/loop',
    '// 2. Make sure the Stigmergy daemon is running (see the start command above).',
    '// 3. Connect once at startup. The loop facade wraps the remote engine so you wire 3 calls,',
    '//    not raw events; if the daemon is down or disabled, every call degrades to a no-op.',
    "import { createRemoteEngine, socketRpcSend } from '@agentic-stigmergy/client'",
    "import { StigmergyLoop } from '@agentic-stigmergy/loop'",
    `const stigmergy = createRemoteEngine(socketRpcSend(${JSON.stringify(sock)}))`,
    'const loop = new StigmergyLoop(stigmergy)',
    '',
    '// 4. Build ONE unified capability set from ALL FOUR explorable sources, each with a STABLE,',
    '//    namespaced id, and register them once at startup with their CORRECT type (not all "tool").',
    '//    Stable ids let the substrate accumulate evidence across turns; consult ranks per type.',
    'const capabilities = [',
    '  ...myTools.map((t) => ({ id: t.name, type: "tool", description: t.description })),',
    "  ...mySkills.map((s) => ({ id: `skill:${s.slug}`, type: 'skill', description: s.description })),",
    "  ...myMcpTools.map((m) => ({ id: `mcp:${m.server}:${m.name}`, type: 'mcp', description: m.description })),",
    "  ...mySubAgents.map((a) => ({ id: `subagent:${a.name}`, type: 'subagent', description: a.description })),",
    ']',
    'for (const c of capabilities) await stigmergy.registerCapability(c) // once; re-run only when the set changes (hash-gated)',
    '',
    '// 5. Per turn: ONE beginTurn over the WHOLE capability set, instrument EVERY invocation, then grade.',
    'const turn = await loop.beginTurn({ task_id: taskId, prompt: userMessage, candidate_ids: capabilities.map((c) => c.id) })',
    '//    Surfacing contract: Stigmergy is RECALL, not a second selector. Keep YOUR OWN tool',
    '//    selection / progressive disclosure as the default; do NOT reorder or narrow the tool block by',
    '//    default -- that competes with your own retrieval and can degrade it. Stigmergy stays silent',
    '//    unless it recognizes the task as one you have already done successfully:',
    'const guidance = turn.pathGuidance((id) => describeById(id)) // a proven path for THIS task, or empty',
    'if (guidance.path.length > 0) {',
    '  //  A confident learned path matched (a sequence/enforce decision). Short-circuit discovery ONLY now:',
    '  //  pre-activate exactly the path capabilities in your host (e.g. activate the deferred tools the',
    '  //  path needs) so the model has them without re-discovering, and inject the small hint AFTER the',
    '  //  cache breakpoint so it never rewrites the cached tool block:',
    '  //    preactivate(guidance.path)                          // host-specific (e.g. activate deferred tools)',
    '  //    messages.push({ role: "user", content: guidance.text })',
    '}',
    '//    When guidance.path is empty (cold / low confidence / no learned path yet), inject NOTHING and let',
    '//    your own selection run unchanged. That is the sweet spot: abbreviate discovery only for tasks',
    '//    already solved successfully. (turn.orderTools exists if you explicitly want pheromone-ordering,',
    '//    but it is NOT the recommended default -- it competes with your retrieval.)',
    '//',
    '//    Trails (tool->tool paths) only form if capability_invoked/returned fire on the path your loop',
    '//    ACTUALLY runs tools on. Pick the case that matches your loop:',
    '//    a) Your loop calls run() on each tool object: wrap them and run the wrapped set.',
    'const instrumented = turn.instrument(myTools.map((t) => ({ id: t.name, run: t.run })))',
    '//       ... run the turn with `instrumented` (its wrapped run reports invoked/returned) ...',
    '//    b) Your loop runs tools through a CENTRAL executor/dispatcher/pipeline and does NOT call run()',
    '//       on the objects above: turn.instrument is bypassed and NO trails form. Hook the dispatch',
    '//       where it runs one tool by name (gate on turn.enabled so a disabled turn stays a no-op):',
    "import { instrumentRun } from '@agentic-stigmergy/loop'",
    'const exec = turn.enabled ? instrumentRun(stigmergy, turn.taskId, toolName, rawExecute) : rawExecute',
    'const result = await exec(...args) // emits capability_invoked before, capability_returned after',
    '//    The SAME dispatch hook applies to EVERY type, with its stable id: tool -> tool.name;',
    "//    skill execution -> `skill:${slug}`; MCP tool call -> `mcp:${server}:${name}`; sub-agent spawn",
    "//    -> `subagent:${name}`. Wrap each where it actually runs, always gated on turn.enabled.",
    'await turn.end()             // the model produced its answer',
    '//    Grade the outcome so ONLY successful paths are learned and promoted (the safety mechanism that',
    '//    keeps a flailing turn from becoming a bad shortcut): accept a clean success, iterate a revision,',
    '//    abandon a failed / no-progress turn.',
    'await turn.accept(tokenCost) // clean success; use turn.iterate() on a revision, turn.abandon() on failure',
    '',
    '// Graceful degrade (every call, every type): when Stigmergy is off in the Studio or the daemon is',
    '// down, beginTurn no-ops the whole turn and every instrumentRun/emit is a swallowed no-op, so tools,',
    '// skills, MCP tools and sub-agents all pass through unwrapped with zero errors -- the loop runs',
    '// exactly as before. Every Stigmergy call is non-fatal; no throw ever escapes into your loop.',
  ].join('\n')
}

/** A prompt the user pastes into their coding agent (Claude Code, Cursor, ...) so the agent wires the
 * daemon-client integration into the loop at the right places. Self-contained: it carries the API, the
 * hook points, the recall-feeds-retrieval surfacing contract (ADR-26), and graceful degrade, so the agent needs no other doc. */
export function buildDaemonClientAgentPrompt(detection: FrameworkDetection, socketPath = ''): string {
  const sock = resolveSocket(socketPath)
  return [
    'You are working in my agent-loop codebase. Integrate Stigmergy as a thin client of an external',
    'Stigmergy daemon, so the loop learns which tools to surface. Stigmergy runs as a separate process',
    '(it owns the embedding model and the database); my loop holds NO engine, model or storage -- only',
    'the client. Stigmergy RECALLS a proven path for a task it has already done successfully; it does NOT',
    'rerank or hide my tools by default. Do not change what the agent can do or invent tools.',
    `Detected framework: ${detection.framework}${detection.integration ? ` (${detection.integration})` : ''}.`,
    '',
    'Do this:',
    '1. Add @agentic-stigmergy/client as a dependency and connect once at startup:',
    '',
    buildDaemonClientRecipe(sock),
    '',
    'Wiring rules:',
    '- Register ALL FOUR explorable capability sources as ONE set, each with its CORRECT type and a',
    '  STABLE namespaced id: function-calling tools -> { id: tool.name, type: "tool" }; skills ->',
    "  { id: `skill:${slug}`, type: 'skill' }; the MCP tools my loop can call -> { id:",
    "  `mcp:${server}:${name}`, type: 'mcp' }; sub-agents/profiles -> { id: `subagent:${name}`, type:",
    "  'subagent' }. registerCapability over the whole set once at startup, hash-gated. Do NOT label",
    '  everything "tool" -- consult ranks per type, and the substrate keys on the stable id.',
    '- ONE consult per turn over the WHOLE set: candidate_ids = every id from all four sources, so tools,',
    '  skills, MCP tools and sub-agents are ranked and surfaced together (orderTools / pathGuidance key on',
    '  the id, so they work unchanged over the unified set).',
    '- Use the StigmergyLoop facade, not raw events: at turn start call loop.beginTurn({ task_id, prompt,',
    '  candidate_ids }) where the candidate tool set is assembled for the model; instrument my tools (see',
    '  the dispatch rule below for how invoked/returned actually fire); call turn.end() when the answer is',
    '  produced, then GRADE the turn: turn.accept(tokenCost) on a clean success, turn.iterate() on a',
    '  revision, turn.abandon() on a failed or no-progress turn. Grading is required -- it is how only',
    '  SUCCESSFUL paths get learned and promoted; a blind accept on every turn would reinforce flailing.',
    '  One stable taskId per turn.',
    '- TRAILS depend on capability_invoked/returned firing on my ACTUAL tool-execution path. First find',
    '  how my loop runs a tool. If it calls run() on the tool object, pass my tools through',
    '  turn.instrument(...) and make sure the loop runs the wrapped objects. If my loop runs tools through',
    '  a central executor/dispatcher/pipeline (it does NOT call run() on the instrumented objects),',
    '  turn.instrument is bypassed and no trails form -- hook that dispatch instead: wrap the real',
    '  per-tool execute with instrumentRun(stigmergy, turn.taskId, toolName, execute) (gate on',
    '  turn.enabled so a disabled turn stays a no-op), or emit capability_invoked before and',
    '  capability_returned (success/failure) after the call. After wiring, verify that invoking a tool',
    '  produces a capability_invoked event.',
    '- Instrument the OTHER THREE types at their real dispatch points too, each with its stable id, so',
    '  trails form across all four: skill execution -> instrumentRun(stigmergy, turn.taskId, `skill:${slug}`,',
    '  run); MCP tool call -> instrumentRun(stigmergy, turn.taskId, `mcp:${server}:${name}`, run); sub-agent',
    '  spawn -> instrumentRun(stigmergy, turn.taskId, `subagent:${name}`, run). If a single central',
    '  dispatcher runs all of them, hook it once and derive the id per type. Every such call stays gated on',
    '  turn.enabled and is non-fatal: when Stigmergy is off or the daemon is down, all four pass through',
    '  unwrapped with zero errors and zero emitted events. Never let a Stigmergy call throw into my loop.',
    '- Surfacing (recall feeds retrieval): Stigmergy is NOT a second tool selector. Keep my own',
    '  tool selection / progressive disclosure (e.g. find_tool) as the default and do NOT reorder or narrow',
    '  the tool block by default -- that competes with my retrieval and can degrade it. Instead call',
    '  turn.pathGuidance(describe). ONLY when it returns a non-empty path (a confident learned path, i.e. a',
    '  sequence/enforce decision) do two things: pre-activate exactly guidance.path in my host (e.g. activate',
    '  the deferred tools that path needs) so the model has them without re-discovering, and inject',
    '  guidance.text as a SMALL per-turn message AFTER the cached system/tools block. When the path is empty',
    '  (cold / low confidence), inject nothing and let my own selection run unchanged. (turn.orderTools',
    '  exists for explicit pheromone-ordering but is not recommended; it competes with my retrieval.)',
    '- Do not add my own enable/disable check: beginTurn already no-ops the whole turn when Stigmergy is',
    '  toggled off or the daemon is down, so the loop runs unchanged in that case.',
    '- Keep every Stigmergy call non-fatal (the facade already degrades; do not let a throw escape).',
    '',
    'Keep the existing behaviour. After wiring, with the daemon running and Stigmergy enabled in the',
    'Studio, the substrate fills with my tools as capabilities and the turns as tasks.',
  ].join('\n')
}
